# Generated by Django 5.0.1 on 2024-01-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0005_reply_parent_reply_alter_reply_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
