# Generated by Django 5.0.1 on 2024-01-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0008_alter_post_photo_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo_field',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
