# Generated by Django 5.0.1 on 2024-01-21 09:28

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0009_alter_post_photo_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo_field',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[320, 240], upload_to='images/'),
        ),
    ]
